version: '3.3'

services:
  cpp:
    build: .
    volumes:
      - ../data/aws-doc-sdk-examples/cpp/example_code/s3/:/data
      - $HOME/.aws/:/root/.aws
    working_dir: /data
    tty: true
    # to use gdb
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined